name: medsam2_cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - pip
  - numpy=1.24.3
  - matplotlib=3.7.2
  - pillow=10.0.0
  - opencv=4.8.0
  - scikit-image=0.21.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - pandas=2.0.3
  - jupyter
  - ipython
  - pip:
      # PyTorch CPU-only installation (official command)
      # Note: Install PyTorch separately with: pip install torch==2.4.0+cpu torchvision==0.19.0+cpu torchaudio==2.4.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
      - acvl-utils==0.2
      - antlr4-python3-runtime==4.9.3
      - argparse==1.4.0
      - batchgenerators==0.25
      - batchgeneratorsv2==0.2
      - connected-components-3d==3.18.0
      - dicom2nifti==2.4.11
      - dynamic-network-architectures==0.3.1
      - einops==0.8.0
      - fft-conv-pytorch==1.2.0
      - hydra-core==1.3.2
      - imagecodecs==2024.6.1
      - imageio==2.34.2
      - iopath==0.1.10
      - monai==1.3.2
      - nibabel==5.2.1
      - nnunetv2==2.5.1
      - omegaconf==2.3.0
      - pydicom==2.4.4
      - python-gdcm==3.0.24.1
      - pyyaml==6.0.1
      - simpleitk==2.3.1
      - synapseclient==4.4.0
      - tensorboardx==2.6.2.2
      - torchsummary==1.5.1
      - tqdm==4.66.4
      - yacs==0.1.8